export const COMMON_MARINE_PARTS = [
  "Main Engine Spares",
  "Auxiliary Engine Spares",
  "Turbocharger Parts",
  "Oily Water Separator",
  "Fresh Water Generator",
  "Air Compressor Spares",
  "Centrifugal Pump",
  "Gear Pump",
  "Screw Pump",
  "Heat Exchanger Gaskets",
  "Fuel Injection Pump",
  "Nozzle Tips",
  "Piston Rings",
  "Cylinder Liner",
  "Cylinder Head",
  "Crankshaft Bearings",
  "Connecting Rod",
  "Exhaust Valve",
  "Intake Valve",
  "Cooling Water Pump",
  "Lubricating Oil Pump",
  "Bilge Pump",
  "Ballast Pump",
  "Fire Pump",
  "Hydraulic Motor",
  "Hydraulic Pump",
  "Deck Crane Spares",
  "Lifeboat Engine Parts",
  "Anchor Windlass Parts",
  "Mooring Winch Parts",
  "Oil Seals",
  "O-Rings Kit",
  "Mechanical Seals",
  "Pressure Gauges",
  "Temperature Sensors",
  "Solvent / Degreaser",
  "Marine Paint",
  "Zinc Anodes",
  "Mooring Ropes",
  "Wire Ropes",
  "Navigation Lights",
  "Safety Equipment",
  "IMO Symbols",
  "Charts & Publications"
];
